# Generated by Django 4.0.4 on 2022-08-30 15:18
import os

from django.contrib.auth import get_user_model
from django.db import migrations


def create_superuser(apps, schema_editor):
    User = get_user_model()

    DJ_SU_FIRST_NAME = os.environ.get('DJ_SU_FIRST_NAME')
    DJ_SU_LAST_NAME = os.environ.get('DJ_SU_LAST_NAME')
    DJ_SU_EMAIL = os.environ.get('DJ_SU_EMAIL')
    DJ_SU_PASSWORD = os.environ.get('DJ_SU_PASSWORD')

    User.objects.create_superuser(
        email=DJ_SU_EMAIL,
        first_name=DJ_SU_FIRST_NAME,
        last_name=DJ_SU_LAST_NAME,
        password=DJ_SU_PASSWORD,
    )


def delete_superuser(apps, schema_editor):
    User = get_user_model()
    admin = User.objects.get(pk=1)
    if admin.is_superuser:
        admin.delete()
    else:
        raise IndexError('User with id = 1 is not an admin')


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_groups'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
