# Generated by Django 4.1 on 2022-09-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
