# Generated by Django 4.0.4 on 2022-09-02 18:46

import customers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[customers.models.validate_length])),
                ('value', models.IntegerField()),
                ('order_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(auto_now=True)),
                ('payment_terms', models.CharField(choices=[('prepayment', 'PREPAYMENT'), ('14 Days NET', '14 DAYS NET'), ('30 Days NET', '30 DAYS NET'), ('60 Days NET', '60 DAYS NET'), ('90 Days NET', '90 DAYS NET')], max_length=100)),
                ('status', models.CharField(choices=[('OVERDUE', 'OVERDUE'), ('CURRENT', 'CURRENT'), ('PAID', 'PAID')], default='CURRENT', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
