# Generated by Django 4.0.4 on 2022-09-09 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_password'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_terms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.paymentterms'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoicestatus'),
        ),
    ]
