# Generated by Django 4.1 on 2022-09-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoicestatus_alter_invoice_payment_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
