# Generated by Django 4.1 on 2022-09-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
