# Generated by Django 4.1 on 2022-09-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_invoice_today_date_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
