# Generated by Django 4.1 on 2022-09-07 19:41

import customers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_terms', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[customers.models.validate_length])),
                ('name', models.CharField(max_length=200)),
                ('bill_to_address', models.CharField(max_length=250)),
                ('ship_to_address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('order_limit', models.IntegerField()),
                ('credit_limit', models.IntegerField()),
                ('credit_limit_currency_code', models.CharField(max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_country', to='customers.customercountry')),
                ('payment_terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment_terms', to='customers.paymentterms')),
                ('sales_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
